rundeck:
    build: ./
    #image: registry.gitlab.itsdonewhenitsdone.net/docker/rundeck:master
    environment:
        SERVER_URL: "https://rundeck.localhost"
        RUNDECK_USER_0: "foo"
        RUNDECK_USER_PASSWORD_0: "bar"
        RUNDECK_USER_PERMISSION_0: "user,admin"
        RUNDECK_USER_1: "joe"
        RUNDECK_USER_MD5_1: "MD5:098f6bcd4621d373cade4e832627b4f6"
        RUNDECK_USER_PERMISSION_1: "user,admin"
    volumes_from:
     - data
    links:
        - database:db
database:
    restart: always
    image: mariadb:10
    environment:
        MYSQL_ROOT_PASSWORD: "rundeck"
        MYSQL_USER: "rundeck"
        MYSQL_DATABASE: "rundeck"
        MYSQL_PASSWORD: "kcednur"
    volumes_from:
     - dbdata
data:
    image: registry.gitlab.itsdonewhenitsdone.net/docker/rundeck:master
    command: --
    entrypoint: /bin/true
dbdata:
    image: mariadb:10
    command: --
    entrypoint: /bin/true
